FROM debian:stretch-slim as grpc_tooling

RUN apt-get update -y && \
    apt-get install -y build-essential dh-autoreconf

ADD external/grpc /home/grpc/external/grpc

RUN cd /home/grpc && \
    cd external/grpc && \
    make clean && make -j8

FROM debian:stretch-slim
COPY --from=grpc_tooling /home/grpc/external/grpc/bins /home/grpc/bins
WORKDIR /home/grpc