name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build-master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout code base.
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Build the Docker image for debian stretch
      run: docker build . --file Dockerfile-debian-slim-stretch --tag rcosnita/grpc-tooling:slim-stretch-latest
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push the tagged Docker image
      run: docker push rcosnita/grpc-tooling:slim-stretch-latest
  
  build-release-debian-slim-stretch:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags') && (contains(github.ref, 'slim-stretch'))
    steps:
    - name: Checkout code base.
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Get current tag name
      uses: olegtarasov/get-tag@v2
      id: tagName
    - name: Build the Docker image for debian stretch
      run: docker build . --file Dockerfile-debian-slim-stretch --tag rcosnita/grpc-tooling:$GIT_TAG_NAME
    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
    - name: Push the tagged Docker image
      run: docker push rcosnita/grpc-tooling:$GIT_TAG_NAME